version: 0.0
os: linux
files:
  - source: /
    destination: /home/codedeploy/test
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstallHook.sh
  AfterInstall:
    - location: scripts/AfterInstallHook.sh 

